version: '3.8'
name: pbtech
services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/fe/src/app
      - /fe/scr/app/node_modules
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - pbtech
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: npm run dev

networks:
  pbtech: