version: '3.8'

services:
  frontend:
    build: ./frontend
    image: missionnick/mission6-frontend
    container_name: mission6
    expose:
      - '3000'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
     
  
      
