version: '3.8'
name: pbtech
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: missionnick/mission6-frontend
    container_name: frontend
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - pbtech
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  pbtech:
     
  
      
